lib/ficdb_web/router.ex
defmodule FicdbWeb.Router do
  use FicdbWeb, :router

  pipeline :browser do
    plug(:accepts, ["html", "json"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(FicdbWeb.Plugs.Veil.UserId)
    plug(FicdbWeb.Plugs.Veil.User)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", FicdbWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", FanficController, :index)
    get("/faq", PageController, :faq)
    get("/changelog", PageController, :changelog)
    post("/add_to_bookshelf/:fanfic_id/:bookshelf_id", BookshelfController, :add_to_bookshelf)
    resources "/fandoms", FandomController
    resources "/fanfics", FanficController
    post("/fanfics/approve/:id", FanficController, :approve)
    post("/fanfics/unapprove/:id", FanficController, :unapprove)
    post("/fanfics/reject/:id", FanficController, :reject)
    post("/fanfics/unreject/:id", FanficController, :unreject)
    post("/fanfics/approval_status/:id", FanficController, :approval_status, as: :approval_status)
    post("/crawl/:host/:id", CrawlerController, :crawl_fanfic)
    post("/crawl/fandom", CrawlerController, :crawl_fandom)
    get("/crawl/characters", CharacterController, :crawl_characters)
    resources "/genres", GenreController
    resources "/reviews", ReviewController
    resources "/suggestions", SuggestionController
    post("/reviews/vote/:id", ReviewController, :vote)

    resources "/characters", CharacterController

    get("/admin/users", AdminController, :users)
    post("/admin/submitter/:id", AdminController, :make_submitter)
    post("/admin/mod/:id", AdminController, :make_mod)
    post("/admin/banned/:id", AdminController, :make_banned)

    get("/veil/users/fanfics", FanficController, :index)


  end

  scope "/veil", FicdbWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", FanficController, :index)
    get("/reviews", ReviewController, :index)
  end

  scope "/veil", FicdbWeb.Veil do
    pipe_through(:browser)

    post("/users/login", UserController, :login)
    post("/users/signup", UserController, :signup)
    put("/users/update", UserController, :update)

    get("/users/new", UserController, :new)
    get("/users/account", UserController, :show)
    get("/users/account/:id", UserController, :show, as: :account)
    get("/users/reviews", UserController, :reviews)
    get("/users/bookshelves/:id", UserController, :bookshelves)
    get("/sessions/new/:request_id", SessionController, :create)
    get("/sessions/signout/:session_id", SessionController, :delete)

  end

end

lib/ficdb_web/controllers/fanfic_controller.ex
defmodule FicdbWeb.FanficController do
  use FicdbWeb, :controller
  use Breadcrumble

  require Logger

  plug :add_breadcrumb, name: "Fanfics", url: "/"
  plug FicdbWeb.Plugs.Authenticate when action not in [:index, :show, :new, :create]
  plug FicdbWeb.Plugs.VerifyRole, [:admin, :mod] when action in [:approve, :unapprove, :reject, :unreject]
  plug FicdbWeb.Plugs.VerifyOwnerOrRole, :fanfic when action in [:edit, :update, :delete]

  alias Ficdb.{Directory, Repo, SchemaHelpers, DateHelpers, EnumHelpers, Authorization}
  alias Ficdb.Directory.{Fanfic, Fandom, Review, Genre, Bookshelf, Character}


  def genre_dropdown_options,
      do: Genre
          |> SchemaHelpers.ordered_by_query
          |> SchemaHelpers.dropdown_format_query
          |> Repo.all

  def approval_status_options(conn)
    do
    case Authorization.verify_role(conn, [:admin, :mod]) do
      {:ok} -> Fanfic.power_user_approval_status_options
      _ -> Fanfic.approval_status_options()
    end
  end


  def character_dropdown_options,
      do: Character
          |> SchemaHelpers.ordered_by_query
          |> SchemaHelpers.dropdown_format_query
          |> Repo.all

  def genre_dropdown_filter,
      do: Genre
          |> SchemaHelpers.ordered_by_query
          |> SchemaHelpers.with_fanfics_query
          |> SchemaHelpers.dropdown_format_query
          |> Repo.all

  def fandom_dropdown_filter,
      do: Fandom
          |> SchemaHelpers.ordered_by_query
          |> SchemaHelpers.with_fanfics_query
          |> SchemaHelpers.dropdown_format_query
          |> Repo.all

  def main_character_filter_options,
      do: Character
          |> SchemaHelpers.ordered_by_query
          |> Character.main_character_dropdown_query
          |> Repo.all

  def relationship_filter_options,
      do: Character
          |> SchemaHelpers.ordered_by_query
          |> Character.relationship_dropdown_query
          |> Repo.all

  def sort_by_options,
      do: Fanfic.sort_by_options

  def fandom_dropdown_options,
      do: Fandom
          |> SchemaHelpers.ordered_by_query
          |> SchemaHelpers.dropdown_format_query
          |> Repo.all

  def word_count_options,
      do: Fanfic.word_count_options
          |> Keyword.keys

  def review_avg_options,
      do: Fanfic.review_avg_options

  def last_chapter_at_options,
      do: Fanfic.last_chapter_at_options
          |> Keyword.keys
          |> List.insert_at(0, nil)

  def current_user_bookshelves(current_user_id),
      do: Bookshelf
          |> Bookshelf.user_bookshelves_query(current_user_id)
          |> Repo.all


  def current_user_reviews(current_user_id) do

    if is_nil(current_user_id) do
      nil
    else
      Review
      |> Review.from_submitter_query(current_user_id)
      |> Repo.one
    end
  end


  def bookshelf_dropdown_options(current_user_id),
      do: Bookshelf
          |> Bookshelf.user_bookshelves_query(current_user_id)
          |> Repo.all
          |> EnumHelpers.get_dropdown_tuple()


  def current_user_bookshelves(nil),
      do: Bookshelf.base_bookshelves()

  def humanize_tuple({a, b}), do: {Phoenix.Naming.humanize(a), b}

  def maturity_options,
      do: Ficdb.MaturityEnum.__enum_map__

  def status_options,
      do: Ficdb.FanficStatusEnum.__enum_map__


  def order_by_options,
      do: Fanfic.order_by_options()

  def sort_by_icons,
      do: Fanfic.sort_by_icons()

  def index(conn, params) do

    start = DateHelpers.now_microseconds

    current_user_id = Authorization.current_user_id(conn)


    with {:ok, query, filter_values} <- Fanfic
                                        |> Fanfic.summary_query(current_user_id)
                                        |> Fanfic.apply_filters(
                                             Map.merge(params, conn.params),
                                             share: [
                                               current_user_id: current_user_id,
                                               params: Map.merge(params, conn.params)
                                             ]
                                           ),
         fanfics <- query
                    |> Repo.all
      do
      render(
        conn,
        "index.html",
        fanfics: fanfics,
        approval_status_options: approval_status_options(conn),
        sort_by_options: sort_by_options(),
        main_character_filter_options: main_character_filter_options(),
        relationship_filter_options: relationship_filter_options(),
        review_avg_options: review_avg_options(),
        word_count_options: word_count_options(),
        status_options: status_options(),
        page_description: Fanfic.page_description(),
        page_options: Fanfic.page_options(),
        maturity_options: maturity_options(),
        last_chapter_at_options: last_chapter_at_options(),
        current_user_id: current_user_id,
        genre_dropdown_options: genre_dropdown_filter(),
        fandom_dropdown_options: fandom_dropdown_filter(),
        current_user_bookshelves: current_user_bookshelves(current_user_id),
        bookshelf_dropdown_options: bookshelf_dropdown_options(current_user_id),
        order_by_options: order_by_options(),
        sort_by_icons: sort_by_icons(),
        character_dropdown_options: character_dropdown_options(),
        filter_values: filter_values,
        items_length: (Enum.at(fanfics, 0) || %{})
                      |> Map.get(:items_length, 1),
        benchmark: DateHelpers.now_microseconds - start,
        current_user_reviews: current_user_reviews(current_user_id)
      )
    else
      err -> IO.inspect(err)
    end
  end



  def new(conn, _params) do
    # should i use repo here?... also, wtf syntax
    changeset = Directory.change_fanfic(
      %Fanfic{}
      |> Fanfic.form_query
    )
    add_breadcrumb(conn, name: "New", url: fanfic_path(conn, :new))
    |> render(
         "new.html",
         changeset: changeset,
         genre_dropdown_options: genre_dropdown_options(),
         fandom_dropdown_options: fandom_dropdown_options(),
         character_dropdown_options: character_dropdown_options(),
         fandom_ids: nil
       )
  end


  def create(conn, %{"fanfic" => fanfic_params}) do
    case Directory.create_fanfic(Authorization.merge_submitter_id(fanfic_params, conn)) do
      {:ok, fanfic} ->
        conn
        |> put_flash(:info, "Fanfic created successfully.")
        |> redirect(to: fanfic_path(conn, :show, fanfic))
      {:error, %Ecto.Changeset{} = changeset} ->


        #### TODO figure out how to load changeset into here
        IO.inspect changeset
        render(
          conn,
          "new.html",
          changeset: update_in(changeset.data, &Repo.preload(&1, [:genres, :fandoms, :primary_relationship])),
          genre_dropdown_options: genre_dropdown_options(),
          fandom_dropdown_options: fandom_dropdown_options(),
          character_dropdown_options: character_dropdown_options()
        )
    end
  end

  def show(conn, %{"id" => id}) do
    current_user_id = Authorization.current_user_id(conn)
    fanfic = Directory.get_fanfic!(id, current_user_id)

    can_review = current_user_id && !(
      Review
      |> Review.review_exists_query(id, current_user_id)
      |> Repo.one)
    review_changeset = fanfic
                       |> Ecto.build_assoc(:reviews)
                       |> Directory.change_review

    suggestion_changeset = fanfic
                           |> Ecto.build_assoc(:suggestions)
                           |> Repo.preload([:genres])
                           |> Ficdb.Directory.Suggestion.changeset(%{})

    render(
      conn,
      "show.html",
      fanfic: fanfic,
      review_changeset: review_changeset,
      suggestion_changeset: suggestion_changeset,
      genre_dropdown_options: genre_dropdown_options,
      approval_status_options: approval_status_options(conn),
      hide_unpoly_target: true,
      can_review: can_review,
      current_user_bookshelves: current_user_bookshelves(current_user_id)
    )
  end

  def edit(conn, %{"id" => id}) do
    current_user_id = Authorization.current_user_id(conn)
    fanfic = conn.assigns.fanfic
    changeset = Directory.change_fanfic(fanfic)
    add_breadcrumb(conn, name: fanfic.name, url: fanfic_path(conn, :show, fanfic))
    |> add_breadcrumb(name: "Edit", url: fanfic_path(conn, :edit, fanfic))
    |> render(
         "edit.html",
         fanfic: fanfic,
         changeset: changeset,
         genre_dropdown_options: genre_dropdown_options(),
         fandom_dropdown_options: fandom_dropdown_options(),
         character_dropdown_options: character_dropdown_options(),
       )

  end

  def update(conn, %{"id" => id, "fanfic" => fanfic_params}) do
    current_user_id = Authorization.current_user_id(conn)
    fanfic = conn.assigns.fanfic

    case Directory.update_fanfic(fanfic, Authorization.merge_updater_id(fanfic_params, conn)) do
      {:ok, fanfic} ->
        conn
        |> put_flash(:info, "Fanfic updated successfully.")
        |> redirect(to: fanfic_path(conn, :show, fanfic))
      {:error, %Ecto.Changeset{} = changeset} ->
        add_breadcrumb(conn, name: fanfic.name, url: fanfic_path(conn, :show, fanfic))
        |> add_breadcrumb(name: "Edit", url: fanfic_path(conn, :edit, fanfic))
        |> render(
             "edit.html",
             fanfic: fanfic,
             changeset: changeset,
             genre_dropdown_options: genre_dropdown_options(),
             fandom_dropdown_options: fandom_dropdown_options(),
             character_dropdown_options: character_dropdown_options()
           )
    end
  end

  def delete(conn, %{"id" => id}) do
    current_user_id = Authorization.current_user_id(conn)
    fanfic = conn.assigns.fanfic

    {:ok, _fanfic} = Directory.delete_fanfic(fanfic)

    conn
    |> put_flash(:info, "Fanfic deleted successfully.")
    |> redirect(to: fanfic_path(conn, :index))
  end

lib/ficdb_web/views/fanfic_view.ex
defmodule FicdbWeb.FanficView do
  use FicdbWeb, :view

  def title("index.html", _assigns) do
    "Ficdb - All Fanfics"
  end

  def title("show.html", %{fanfic: fanfic} = assigns) do
    "Ficdb - #{fanfic.name}"
  end

  def title("edit.html", _assigns) do
    "Ficdb - Edit Fanfic"
  end

  def title(_, _assigns) do
    "Ficdb - Fanfics"
  end

end

lib/ficdb_web/templates/fanfic/_scrape_input.html.eex
<div class="flex-1">
    <label class="block flex items-center"><span class="inline-block mr-1"><img class="h-4" src="<%= static_path(@conn, "/images/host_icons/#{@host}.png")%>"/> </span> <%=@host_name %></label>
    <a data-tippy-content="<span>https://www.fictionpress.com/s/<u><b>2961893</b></u>/1/Mother-of-Learning <br/><br/> <u><b>2961893</b></u> = Thread ID</span>" uk-icon="icon: question; ratio: .9;"></a></label>
    <%= number_input @f, @form_name, placeholder: "123456", class: "mr-2" %>
    <a class="label-text mt-2 button" data-host="<%= @host %>" data-crawl-fanfic="true" >Scrape</a>
    <%= error_tag @f, @form_name %>
</div>

lib/ficdb_web/templates/fanfic/edit.html.eex
<%= render "form.html", Map.put(assigns, :action, fanfic_path(@conn, :update, @fanfic)) %>

lib/ficdb_web/templates/fanfic/filter.html.eex
<%= form_for @conn, fanfic_path(@conn, :index), [as: :search, method: :get, "up-dash": "#up-results", "up-autosubmit": true, id: "menu"], fn f -> %>

<div class="container mx-auto">
    <div class="tracking-wide text-xs ">


        <a class="pb-8 inline-block md:hidden mb-2 text-center button mx-auto" data-toggle=".mobile-toggle">Filter Results</a>


        <div class="mobile-toggle hidden md:block">


            <div class="filter flex flex-wrap">


                <div class="w-full sm:w-1/2 md:w-1/3 lg:w-1/5 pr-3 py-3 ">
                    <span class="mb-2"><i class="jam jam-search text-xl inline-block align-middle inset-b-2px relative"></i></span>
                    Filter by Title/Author
                    <div class="mt-2">
                        <%= text_input f, :title, class: "w-full", placeholder: "" %>
                    </div>
                </div>

                <div class="w-full sm:w-1/2 md:w-1/3 lg:w-1/5 px-3 py-3 ">
                    <span class="mb-2"><i class="jam jam-bug text-xl inline-block align-middle inset-b-2px relative"></i></span>
                    Filter by Fandoms
                    <div class="mt-2">
                        <%= multiple_select f, :fandoms, @fandom_dropdown_options, placeholder: "+ Include", class: "include" %>
                        <div class="extras">
                            <%= multiple_select f, :anti_fandoms, @fandom_dropdown_options, placeholder: "- Exclude", class: "mt-1 exclude" %>
                        </div>
                    </div>
                </div>

                <div class="w-full sm:w-1/2 md:w-1/3 lg:w-1/5 px-3 py-3 ">
                    <span class="mb-2"><i class="jam jam-sword text-xl inline-block align-middle inset-b-2px relative"></i></span>
                    Filter by Genres
                    <div class="mt-2">
                        <%= multiple_select f, :genres, @genre_dropdown_options, placeholder: "+ Include", class: "include" %>
                        <div class="extras">
                            <%= multiple_select f, :anti_genres, @genre_dropdown_options, placeholder: "- Exclude", class: "mt-1 exclude" %>
                        </div>
                    </div>
                </div>

                <div class="w-full sm:w-1/2 md:w-1/3 lg:w-1/5 whitespace-no-heart px-3 py-3 ">
                    <span class="mb-2"><i class="jam jam-heart text-xl inline-block align-middle inset-b-2px relative"></i></span>
                    Filter by Relationships
                    <div class="mt-2">
                        <%= multiple_select f, :primary_relationship, @relationship_filter_options, placeholder: "+ Include", class: "include" %>
                        <div class="extras">
                            <%= multiple_select f, :anti_primary_relationship, @relationship_filter_options, placeholder: "- Exclude", class: "mt-1 exclude" %>
                        </div>
                    </div>
                </div>

                <div class="w-full sm:w-1/2 md:w-1/3 lg:w-1/5 pl-3 py-3 ">
                    <span class="mb-2"><i class="jam jam-user-square text-xl inline-block align-middle inset-b-2px relative"></i></span>
                    Filter by Protagonist
                    <div class="mt-2">
                        <%= multiple_select f, :main_character_id, @main_character_filter_options, placeholder: "+ Include", class: "include" %>
                        <div class="extras">
                            <%= multiple_select f, :anti_main_character_id, @main_character_filter_options, placeholder: "- Exclude", class: "mt-1 exclude" %>
                        </div>
                    </div>
                </div>

            </div>

            <div class="extras">
                <div class="filter  flex flex-wrap items-center -whitest">


                    <div class=" w-full sm:w-1/2 md:w-1/3 lg:w-1/4 pr-3 py-3 ">
                        <span class="mb-2"><i class="jam jam-language text-xl inline-block align-middle inset-b-2px relative"></i></span>
                        Word Count
                        <div class="mt-2">
                            <%= multiple_select f, :word_count, @word_count_options, placeholder: "+ Include", class: "include" %>
                            <%= multiple_select f, :anti_word_count, @word_count_options, placeholder: "- Exclude", class: "mt-1 exclude" %>
                        </div>
                    </div>
                    <div class=" w-full sm:w-1/2 md:w-1/3 lg:w-1/4 px-3 py-3 ">
                        <span class="mb-2"><i class="jam jam-triangle-danger text-xl inline-block align-middle inset-b-2px relative"></i></span>
                        Maturity
                        <div class="mt-2">
                            <%= multiple_select f, :maturity, @maturity_options, placeholder: "+ Include", class: "include" %>
                            <%= multiple_select f, :anti_maturity, @maturity_options, placeholder: "- Exclude", class: "mt-1 exclude" %>
                        </div>
                    </div>
                    <div class=" w-full sm:w-1/2 md:w-1/3 lg:w-1/4 px-3 py-3 ">
                        <span class="mb-2"><i class="jam jam-activity text-xl inline-block align-middle inset-b-2px relative"></i></span>
                        Status
                        <div class="mt-2">
                            <%= multiple_select f, :status, @status_options, placeholder: "+ Include", class: "include" %>
                            <%= multiple_select f, :anti_status, @status_options, placeholder: "- Exclude", class: "mt-1 exclude" %>
                        </div>
                    </div>

                    <%= if @conn.assigns[:veil_user_id] do %>

                    <div class=" w-full sm:w-1/2 md:w-1/3 lg:w-1/4 pl-3 py-3 ">
                        <span class="mb-2"><i class="jam jam-book text-xl inline-block align-middle inset-b-2px relative"></i></span>
                        Bookshelves
                        <div class="mt-2">
                            <%= multiple_select f, :bookshelves, @bookshelf_dropdown_options, placeholder: "+ Include", class: "include" %>
                            <%= multiple_select f, :anti_bookshelves, @bookshelf_dropdown_options, placeholder: "- Exclude", class: "mt-1 exclude" %>
                        </div>
                    </div>

                    <% end %>

                </div>
                 <div class="flex flex-wrap items-center">
                                        <%= label f, :show_description_and_hosts, class: "m-0" %>&nbsp;
                                        <%= checkbox f, :show_description, class: "mb-1" %>&nbsp;
                                        </div>
                                                                <div class="flex flex-wrap items-center">

                                        <%= label f, :show_only_crossovers, class: "m-0" %>&nbsp;
                                        <%= checkbox f, :show_crossovers, class: "mb-1" %>&nbsp;
                                        </div>
                                                                <div class="flex flex-wrap items-center">

                                        <%= label f, :hide_crossovers, class: "m-0" %>&nbsp;
                                        <%= checkbox f, :hide_crossovers, class: "" %>&nbsp;
                                        </div>
            </div>
            <div class="flex mt-2 items-center">

            <div class="flex-1 text-teal-light"><a class="inline-block toggle-trigger text-xs uppercase" data-toggle=".extras">Additional Filters <i data-toggle=".extras" class="jam jam-chevron-down text-xl inline-block align-middle inset-b-2px relative arrow"></i></a></div>

            <%= render FicdbWeb.SharedView, "_links_and_user_stats.html", Map.merge(assigns, %{f: f}) %>


        </div>
        </div>
    </div>
</div>
<% end %>

lib/ficdb_web/templates/fanfic/index.html.eex
<%= Ficdb.Authorization.render(Ficdb.Authorization.authenticate(@conn), render(FicdbWeb.SharedView, "_top_right_action.html", helper: "New", text: "New Fanfic", path: fanfic_path(@conn, :new))) %>

<div id="index">

<%= render FicdbWeb.FanficView, "filter.html", assigns %>

<%= render FicdbWeb.SharedView, "_result_list.html", assigns %>

</div>

lib/ficdb_web/templates/fanfic/message.html.eex
<div class="uk-alert uk-position-relative message" uk-alert>
    <div class="uk-flex-middle uk-grid-small uk-grid" uk-grid>
        <div class="uk-width-auto">
        <img width="80" src="<%= static_path(@conn, "/images/skitter.png") %>"/>
        </div>

       <div class="uk-width-expand">
        Welcome to Ficdb <small>(v0.1)</small>, a platform to discover, review, and share fanfics and web serials worth reading.

        Check out our <%= link "FAQ page", to: page_path(@conn, :faq), class: "uk-preserve-color uk-text-bold", "up-dash": "main" %>
        and our <a href="https://discord.gg/uRrEHfV" class="uk-preserve-color uk-text-bold">Discord community</a>!
        </div>
    </div>
</div>

lib/ficdb_web/templates/fanfic/new.html.eex
<%= render "form.html", Map.put(assigns, :action, fanfic_path(@conn, :create)) %>

lib/ficdb_web/templates/fanfic/save_filter.html.eex
<div class="">

        <div class="mb-2">
            <%= multiple_select @f, :word_count, @word_count_options, placeholder: "Word Count" %>
            <%= error_tag @f, :word_count %>
        </div>

        <div class="mb-2">
            <%= multiple_select @f, :maturity, @maturity_options, placeholder: "Maturity" %>
            <%= error_tag @f, :maturity %>
        </div>

        <div class="mb-2">
            <%= multiple_select @f, :status, @status_options, placeholder: "Status" %>
            <%= error_tag @f, :status %>
        </div>
        <div class="mb-2">
        <div class="selectize-input">
                            <%= text_input @f, :title, class: "", placeholder: "Search Titles..." %>
                            <%= error_tag @f, :title %>
        </div>
        </div>
    </div>

 <div class="" style="margin-top: 3px" id="selectize-parent" uk-grid="">
    </div>

lib/ficdb_web/templates/fanfic/show.html.eex
           <div id="up-results">

<%= render FicdbWeb.SharedView, "_result_item.html", Map.merge(assigns, %{:item => @fanfic, :idx => nil, :path => fanfic_path(@conn, :edit, @fanfic.id)}) %>
<%= render FicdbWeb.SharedView, "_review_list.html", conn: @conn, reviews: @fanfic.reviews %>
<%= render FicdbWeb.SuggestionView, "form.html", conn: @conn, action: suggestion_path(@conn, :create), changeset: @suggestion_changeset, genre_dropdown_options: @genre_dropdown_options  %>
<%= render FicdbWeb.SharedView, "_suggestion_list.html", conn: @conn, item: @fanfic  %>



       </div>