lib/ficdb_web/router.ex
defmodule FicdbWeb.Router do
  use FicdbWeb, :router

  pipeline :browser do
    plug(:accepts, ["html", "json"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(FicdbWeb.Plugs.Veil.UserId)
    plug(FicdbWeb.Plugs.Veil.User)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", FicdbWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", FanficController, :index)
    get("/faq", PageController, :faq)
    get("/changelog", PageController, :changelog)
    post("/add_to_bookshelf/:fanfic_id/:bookshelf_id", BookshelfController, :add_to_bookshelf)
    resources "/fandoms", FandomController
    resources "/fanfics", FanficController
    post("/fanfics/approve/:id", FanficController, :approve)
    post("/fanfics/unapprove/:id", FanficController, :unapprove)
    post("/fanfics/reject/:id", FanficController, :reject)
    post("/fanfics/unreject/:id", FanficController, :unreject)
    post("/fanfics/approval_status/:id", FanficController, :approval_status, as: :approval_status)
    post("/crawl/:host/:id", CrawlerController, :crawl_fanfic)
    post("/crawl/fandom", CrawlerController, :crawl_fandom)
    get("/crawl/characters", CharacterController, :crawl_characters)
    resources "/genres", GenreController
    resources "/reviews", ReviewController
    resources "/suggestions", SuggestionController
    post("/reviews/vote/:id", ReviewController, :vote)

    resources "/characters", CharacterController

    get("/admin/users", AdminController, :users)
    post("/admin/submitter/:id", AdminController, :make_submitter)
    post("/admin/mod/:id", AdminController, :make_mod)
    post("/admin/banned/:id", AdminController, :make_banned)

    get("/veil/users/fanfics", FanficController, :index)


  end

  scope "/veil", FicdbWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", FanficController, :index)
    get("/reviews", ReviewController, :index)
  end

  scope "/veil", FicdbWeb.Veil do
    pipe_through(:browser)

    post("/users/login", UserController, :login)
    post("/users/signup", UserController, :signup)
    put("/users/update", UserController, :update)

    get("/users/new", UserController, :new)
    get("/users/account", UserController, :show)
    get("/users/account/:id", UserController, :show, as: :account)
    get("/users/reviews", UserController, :reviews)
    get("/users/bookshelves/:id", UserController, :bookshelves)
    get("/sessions/new/:request_id", SessionController, :create)
    get("/sessions/signout/:session_id", SessionController, :delete)

  end

end

lib/ficdb_web/views/shared_view.ex
defmodule FicdbWeb.SharedView do
  use FicdbWeb, :view

  def title(_, _assigns) do
    "Ficdb - Shared"
  end

  def current_approval_status(fanfic)
    do
    answer = cond do
      not is_nil(fanfic.rejector_id) ->  "rejected"
      not is_nil(fanfic.approver_id) -> "approved"
      is_nil(fanfic.rejector_id) && is_nil(fanfic.approver_id) ->  "unapproved"
      true ->  "unapproved"
    end
  end

  def current_approval_status_human(fanfic)
    do
    answer = cond do
      not is_nil(fanfic.rejector_id) ->  "Rejected"
      is_nil(fanfic.rejector_id) && is_nil(fanfic.approver_id) ->  "Unapproved"
      true ->  ""
    end
  end
end

lib/ficdb_web/templates/shared/_add_to_bookshelf_button.html.eex
 <span class="py-1 px-3 border-grey border rounded-lg text-grey">
     <a data-toggle="<%= "#bk-#{@item.id}" %>" class="add-to-bookshelf">
         <i class="jam jam-book text-lg inline-block align-middle pb-px mb-px -mr-1"></i> Bookshelf
     </a>
 </span>

lib/ficdb_web/templates/shared/_benchmark.html.eex
<%= if assigns[:benchmark] do %><div class=""><div class="border mt-4 rounded-lg p-2 text-sm inline-block absolute z-50"><%= length @list %> results &middot; <%= max(0.0001, @benchmark/1000000) %> seconds</div></div><% end %>

lib/ficdb_web/templates/shared/_current_bookshelf.html.eex
<%= if @item.current_user_bookshelf_names do %>
<%= link to: fanfic_path(@conn, :index, Ficdb.EnumHelpers.set_nested_param(@conn.params, ["search", "bookshelves"], [@item.current_user_bookshelf.bookshelf.id])), class: "text-green-light hover:text-green whitespace-no-wrap" do %>
<i class="jam jam-book text-xl inline-block align-middle inset-b-1 mt-px pt-px mr-px pr-px relative"></i><span class=""><%= Phoenix.Naming.humanize @item.current_user_bookshelf_names %></span>
<% end %>
<% end %>

lib/ficdb_web/templates/shared/_delete_tag.html.eex
<%= if (assigns[:item_path]) do %><span class="uk-text-muted uk-text-xs text-red"> &middot;
                    <a ujs-method="delete" ujs-remote ujs-confirm="Are you sure you want to delete this? Make sure to remove all associated fanfics first!" href="<%=  @item_path.(@conn, :delete, @item) %>">Delete</a>
</span>
<% end %>

lib/ficdb_web/templates/shared/_edit_button.html.eex
<span class="py-1 px-3 border-grey border rounded-lg text-grey">
    <a href="<%= fanfic_path(@conn, :edit, @item.id) %>" class="">
        Edit
    </a>
</span>

lib/ficdb_web/templates/shared/_fandom_list.html.eex
<span class="whitespace-no-wrap">
  [<%= for {fandom, idx} <- Enum.with_index @fandoms do %>
  <%= link fandom.name, to: fanfic_path(@conn, :index, Ficdb.EnumHelpers.push_nested_param(@conn.params, ["search", "fandoms"], fandom.id)), "up-dash": "main", class: "" %>
  <%= if idx + 1 < length @fandoms do %>
   <i class="jam jam-arrows-fullscreen inline-block align-middle inset-b-2px relative"></i>
   <% end %>
  <% end %>]
</span>

lib/ficdb_web/templates/shared/_form_error_banner.html.eex
<%= if @changeset.action do %>
    <div class="uk-alert-danger" uk-alert>
        <a class="uk-alert-close" uk-close></a>
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

lib/ficdb_web/templates/shared/_primary_relationship_list.html.eex
<%= if length(@primary_relationship) > 0 do %>
<span class="mr-1 text-red-light hover:text-red">
  <%= link to: fanfic_path(@conn, :index, Ficdb.EnumHelpers.set_nested_param(@conn.params, ["search", "primary_relationship"], @primary_relationship |> Ficdb.SchemaHelpers.pluck(:id) )), "up-dash": "main", class: "" do %>
  <i class="jam jam-heart text-xl inline-block align-middle relative inset-b-1 mt-1 inset-l-3px"></i>
  <%= for {character, idx} <- Enum.with_index @primary_relationship do %>
  <%= character.name %>
  <%= if idx + 1 < length @primary_relationship do %>
  ×
  <% end %>
  <% end %>
  <% end %>
</span>
  <% end %>

lib/ficdb_web/templates/shared/_result_list.html.eex
<div class="pt-6" id="up-results">

         <%= render FicdbWeb.SharedView, "_pagination.html", assigns %>

<div class="pt-4">

    <%= for {item, idx} <- Enum.with_index(@fanfics) do %>
           <%= render "_result_item.html", Map.merge(assigns, %{item: item, idx: idx}) %>
    <% end %>

     <%= render FicdbWeb.SharedView, "_pagination.html", assigns %>

</div>
</div>

lib/ficdb_web/templates/shared/_review_item.html.eex
<article class="pb-8 pt-6 px-6 border-albino border-b mb-2 last-child-borderless no-underline group" id="<%= " review-#{@review.id}" %>">
    <header class="flex items-center">
        <div class="">
            <%= render FicdbWeb.SharedView, "_avatar.html", image: @review.submitter.image, model: @review.submitter, class: "uk-border-rounded-lg" %>
        </div>
        <div class="flex-1 pl-4">
            <span class="jquery-stars inline-block align-middle h-5" data-stars="<%= @review.rating %>"></span>
            <span class="text-lg"><%= @review.headline %></span>
            <div class="uppercase text-sm text-whitest mt-1">
                <span>
                    <%= link @review.submitter.username , to: account_path(@conn, :show, @review.submitter.id), class: "", "up-dash": "main" %></span>
                <span class="px-2">|</span>
                <span>
                    <%= relative(@review.inserted_at) %>
                    <%= if @review.updater_id do %><span class="">*</span>
                    <% end %></span>


                <%= if Ecto.assoc_loaded?(@review.fanfic) do %>
                <span class="px-2">|</span>

                    <%= link @review.fanfic.name, to: fanfic_path(@conn, :show, @review.fanfic.id), class: "text-white", "up-dash": "#up-results" %>
                <% end %>
            </div>
        </div>


    </header>

<%= if @review.content do %>
    <div class="pl-16">
        <div class="text-grey overflow-hidden" data-read-more="true">
            <p class="whitespace-pre-wrap">
                <%= @review.content %>
            </p>
        </div>
        </div>
<% end %>

<%= if @review.headline do %>
<div class="flex flex-wrap items-center pl-16 mt-4">

<% is_reviewer = @conn.assigns[:veil_user_id] == @review.submitter_id %>

    <a ujs-method="post" ujs-remote data-vote="true" href="<%= if is_reviewer || is_nil(@conn.assigns[:veil_user_id]), do: "false", else: "/reviews/vote/#{@review.id}" %>" class="flex rounded-lg flex items-center no-underline uppercase px-2 py-px text-sm font-bold
        <%= if @conn.assigns[:veil_user_id] in (@review.votes |> Ficdb.SchemaHelpers.pluck(:submitter_id)), do: "bg-red-light", else: "bg-purple-light" %>">
        <i class="jam jam-heart-f text-xl inline-block align-middle pb-px mb-px"></i>
        <span class="pl-1" data-vote-count="true"><%= length(@review.votes) %></span>
    </a>

    <%= for voter <- @review.votes do %>
               <span class="pl-2 text-red-light opacity-0 group-hover:opacity-100 transition-fast"><%= voter.submitter.username %></span>
        <% end %>
</div>
<% end %>


</article>

lib/ficdb_web/templates/shared/_review_list.html.eex
<% reviews_with_headline = @reviews |> Enum.filter(fn review -> !!review.headline end) %>
<% reviews_without_text = @reviews |> Enum.filter(fn review -> !review.headline end) %>

<div class="border-albino bg-black-light rounded-lg mb-4">
<%= for {review, _idx} <- Enum.with_index(reviews_with_headline) do %>
   <%= render FicdbWeb.SharedView, "_review_item.html", conn: @conn, review: review %>
<% end %>
<%= for {review, _idx} <- Enum.with_index(reviews_without_text) do %>
   <%= render FicdbWeb.SharedView, "_review_item.html", conn: @conn, review: review %>
<% end %>
</div>

lib/ficdb_web/templates/shared/_ribbon.html.eex
<%= cond do %>
<% Timex.after?(@item.last_chapter_at, Timex.shift(Timex.now, days: -1)) -> %>
     <div class="ribbon right new"><span>New Today!</span></div>
<% Timex.after?(@item.last_chapter_at, Timex.shift(Timex.now, days: -7)) -> %>
  <div class="ribbon right"><span>New Chapter</span></div>
<% true -> %>
  <!-- nothing -->
<% end %>

lib/ficdb_web/templates/shared/_suggestion_list.html.eex
<%= for suggestion <- @item.suggestions do %>
   <%= render FicdbWeb.SharedView, "_suggestion_item.html", conn: @conn, suggestion: suggestion %>
<% end %>

lib/ficdb_web/templates/shared/_top_right_action_no_unpoly.html.eex
<span class="uk-position-top-right uk-padding">
    <%= link to: @path, class: "button" do %>
    <%= @text %>
    <% end %>
</span>