lib/ficdb_web/router.ex
defmodule FicdbWeb.Router do
  use FicdbWeb, :router

  pipeline :browser do
    plug(:accepts, ["html", "json"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(FicdbWeb.Plugs.Veil.UserId)
    plug(FicdbWeb.Plugs.Veil.User)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", FicdbWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", FanficController, :index)
    get("/faq", PageController, :faq)
    get("/changelog", PageController, :changelog)
    post("/add_to_bookshelf/:fanfic_id/:bookshelf_id", BookshelfController, :add_to_bookshelf)
    resources "/fandoms", FandomController
    resources "/fanfics", FanficController
    post("/fanfics/approve/:id", FanficController, :approve)
    post("/fanfics/unapprove/:id", FanficController, :unapprove)
    post("/fanfics/reject/:id", FanficController, :reject)
    post("/fanfics/unreject/:id", FanficController, :unreject)
    post("/fanfics/approval_status/:id", FanficController, :approval_status, as: :approval_status)
    post("/crawl/:host/:id", CrawlerController, :crawl_fanfic)
    post("/crawl/fandom", CrawlerController, :crawl_fandom)
    get("/crawl/characters", CharacterController, :crawl_characters)
    resources "/genres", GenreController
    resources "/reviews", ReviewController
    resources "/suggestions", SuggestionController
    post("/reviews/vote/:id", ReviewController, :vote)

    resources "/characters", CharacterController

    get("/admin/users", AdminController, :users)
    post("/admin/submitter/:id", AdminController, :make_submitter)
    post("/admin/mod/:id", AdminController, :make_mod)
    post("/admin/banned/:id", AdminController, :make_banned)

    get("/veil/users/fanfics", FanficController, :index)


  end

  scope "/veil", FicdbWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", FanficController, :index)
    get("/reviews", ReviewController, :index)
  end

  scope "/veil", FicdbWeb.Veil do
    pipe_through(:browser)

    post("/users/login", UserController, :login)
    post("/users/signup", UserController, :signup)
    put("/users/update", UserController, :update)

    get("/users/new", UserController, :new)
    get("/users/account", UserController, :show)
    get("/users/account/:id", UserController, :show, as: :account)
    get("/users/reviews", UserController, :reviews)
    get("/users/bookshelves/:id", UserController, :bookshelves)
    get("/sessions/new/:request_id", SessionController, :create)
    get("/sessions/signout/:session_id", SessionController, :delete)

  end

end

lib/ficdb_web/views/layout_view.ex
defmodule FicdbWeb.LayoutView do
  use FicdbWeb, :view

  def render_layout(layout, assigns, do: content) do
    render(layout, Map.put(assigns, :inner_layout, content))
  end

  def title(_, _assigns) do
    "Ficdb - Layout"
  end
end

lib/ficdb_web/templates/layout/_navigation.html.eex
<div class="flex flex-wrap tracking-wide items-center content-start	 text-white md:text-center mx-4 mt-6" up-nav>
        <div class="inline-block md:flex-1 hidden md:block">
            <%= link to: fanfic_path(@conn, :index), class: "", "up-dash": "main" do %>
                <img width="140" src="<%= static_path(@conn, "/images/logo.svg")%>"/>
            <% end %>
        </div>

        <div class="inline-block md:flex-1">

                    <%= active_link(@conn, to: fanfic_path(@conn, :index), active: ~r/[\s\S]*/, class: "no-underline inline-flex items-center inline-flex items-center", "up-dash": "main", "up-alias": "/ /fanfics/* /?*") do %>
                    <span class="diamond invisible md:visible">
                                    <span class="border"></span>
                                    <span class="back"></span>
                                  </span>
                        <span class="elastic-line ml-3">FANFICS</span>
                    <% end %>
                </div>


        <div class="inline-block md:flex-1">
                    <%= active_link(@conn, to: review_path(@conn, :index), class: "no-underline inline-flex items-center", "up-dash": "main",  "up-alias": "/reviews") do %>
                    <span class="diamond invisible md:visible">
                                                <span class="border"></span>
                                                <span class="back"></span>
                                              </span>
                        <span class="elastic-line ml-3">REVIEWS</span>
                    <% end %>
                </div>


        <div class="inline-block md:flex-1">
            <%= active_link(@conn, to: fandom_path(@conn, :index), class: "no-underline inline-flex items-center", "up-dash": "main",  "up-alias": "/fandoms*") do %>
            <span class="diamond invisible md:visible">
                                        <span class="border"></span>
                                        <span class="back"></span>
                                      </span>
                <span class="elastic-line ml-3">FANDOMS</span>
            <% end %>
        </div>

        <div class="inline-block md:flex-1">
            <%= active_link(@conn, to: genre_path(@conn, :index), class: "no-underline inline-flex items-center", "up-dash": "main",  "up-alias": "/genres*") do %>
            <span class="diamond invisible md:visible">
                                        <span class="border"></span>
                                        <span class="back"></span>
                                      </span>
                <span class="elastic-line ml-3">GENRES</span>
            <% end %>
        </div>

        <%= render "_veil_auth_or_user.html", assigns %>


</div>

lib/ficdb_web/templates/layout/_veil_auth_or_user.html.eex
    <div class="flex-1">
        <%= if assigns[:veil_user_id] do %>
           <%= active_link(@conn, to: user_path(@conn, :show), class: "no-underline inline-flex items-center", "up-dash": "main", "up-alias": "/veil*") do %>
                       <span class="diamond md:visible invisible">
                           <span class="border"></span>
                           <span class="back"></span>
                         </span>
                           <span class="elastic-line ml-3">ACCOUNT</span>
                       <% end %>
          <% else %>
            <%= active_link(@conn, to: user_path(@conn, :new), class: "no-underline inline-flex items-center", "up-dash": "main") do %>
            <span class="diamond md:visible invisible">
                <span class="border"></span>
                <span class="back"></span>
              </span>
                <span class="elastic-line ml-3">LOGIN / SIGNUP</span>
            <% end %>
          <% end %>
    </div>

lib/ficdb_web/templates/layout/app.html.eex
    <!DOCTYPE html>
<html lang="en">
  <head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-127033995-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-127033995-1');
  </script>

      <%= csrf_meta_tag() %>


    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="google-site-verification" content="G9DnKDOqBlyBgz3_lNAJf5haUTCrmFG9w8oiR07JSKw" />
        <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">

<link href="https://fonts.googleapis.com/css?family=Montserrat|Muli:300,400,700" rel="stylesheet">
<link rel="stylesheet" href="https://unpkg.com/jam-icons@2.0.0/css/jam.min.css">
    <script async src="https://unpkg.com/delayed-scroll-restoration-polyfill@0.1.1/index.js"></script>


<title><%= @view_module.title(@view_template, assigns) %></title>
     <script>// DO NOT REMOVE EMPTY SCRIPT TAG - resolves initial animaiton flicker bug - https://bugs.chromium.org/p/chromium/issues/detail?id=332189</script>
     <script async src="<%= static_path(@conn, "/js/app.js") %>"></script>

  </head>



  <body class="bg-black font-sans pb-12">
  <div id="page">

      <%= render "_navigation.html", assigns %>
      <main class="container mx-auto text-white relative" role="main">

      <%= render Ficdb.BreadcrumbleView, "breadcrumb.html", breadcrumb_trails: assigns[:breadcrumb_trails], conn: @conn %>

      <%= if get_flash(@conn, :info) do %><div class="border border-blue-light rounded-lg mb-2 bg-blue-lightest px-4 py-3 text-blue-dark">
      <%= get_flash(@conn, :info) %></div><% end %>
      <%= if get_flash(@conn, :error) do %><div class="border border-red-light rounded-lg mb-2 bg-red-lightest px-4 py-3 text-red-dark">
      <%= get_flash(@conn, :error) %></div><% end %>

        <%= Map.get(assigns, :inner_layout) || render @view_module, @view_template, assigns %>

      </main>





   </div>






  </body>
</html>