lib/ficdb_web/router.ex
defmodule FicdbWeb.Router do
  use FicdbWeb, :router

  pipeline :browser do
    plug(:accepts, ["html", "json"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(FicdbWeb.Plugs.Veil.UserId)
    plug(FicdbWeb.Plugs.Veil.User)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", FicdbWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", FanficController, :index)
    get("/faq", PageController, :faq)
    get("/changelog", PageController, :changelog)
    post("/add_to_bookshelf/:fanfic_id/:bookshelf_id", BookshelfController, :add_to_bookshelf)
    resources "/fandoms", FandomController
    resources "/fanfics", FanficController
    post("/fanfics/approve/:id", FanficController, :approve)
    post("/fanfics/unapprove/:id", FanficController, :unapprove)
    post("/fanfics/reject/:id", FanficController, :reject)
    post("/fanfics/unreject/:id", FanficController, :unreject)
    post("/fanfics/approval_status/:id", FanficController, :approval_status, as: :approval_status)
    post("/crawl/:host/:id", CrawlerController, :crawl_fanfic)
    post("/crawl/fandom", CrawlerController, :crawl_fandom)
    get("/crawl/characters", CharacterController, :crawl_characters)
    resources "/genres", GenreController
    resources "/reviews", ReviewController
    resources "/suggestions", SuggestionController
    post("/reviews/vote/:id", ReviewController, :vote)

    resources "/characters", CharacterController

    get("/admin/users", AdminController, :users)
    post("/admin/submitter/:id", AdminController, :make_submitter)
    post("/admin/mod/:id", AdminController, :make_mod)
    post("/admin/banned/:id", AdminController, :make_banned)

    get("/veil/users/fanfics", FanficController, :index)


  end

  scope "/veil", FicdbWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", FanficController, :index)
    get("/reviews", ReviewController, :index)
  end

  scope "/veil", FicdbWeb.Veil do
    pipe_through(:browser)

    post("/users/login", UserController, :login)
    post("/users/signup", UserController, :signup)
    put("/users/update", UserController, :update)

    get("/users/new", UserController, :new)
    get("/users/account", UserController, :show)
    get("/users/account/:id", UserController, :show, as: :account)
    get("/users/reviews", UserController, :reviews)
    get("/users/bookshelves/:id", UserController, :bookshelves)
    get("/sessions/new/:request_id", SessionController, :create)
    get("/sessions/signout/:session_id", SessionController, :delete)

  end

end

lib/ficdb/helpers/user_helpers.ex
defmodule Ficdb.UserHelpers do

  def topic_owner?(%{id: id}, %{submitter_id: submitter_id}) do
    id == submitter_id
  end

  def topic_owner?(_, _), do: false

end

lib/ficdb/veil/clean.ex
defmodule Ficdb.Veil.Clean do
  @moduledoc """
  Used alongside Quantum to schedule regular pruning of the database
  """

  alias Ficdb.Veil

  @doc """
  Delete all expired requests and sessions
  """
  def expired do
    Task.start(fn -> Veil.delete_expired_requests() end)
    Task.start(fn -> Veil.delete_expired_sessions() end)
  end
end

lib/ficdb/veil/request.ex
defmodule Ficdb.Veil.Request do
  @moduledoc """
  Veil's Request Schema - a request is a login attempt
  """
  use Ecto.Schema
  import Ecto.Changeset
  alias Ficdb.Veil.User

  schema "veil_requests" do
    field(:unique_id, :string)
    field(:phoenix_token, :string)
    field(:ip_address, :string)
    belongs_to(:user, User)

    timestamps()
  end

  def changeset(model, params \\ %{}) do
    model
    |> cast(params, [:unique_id, :phoenix_token, :user_id, :ip_address])
    |> validate_required([:unique_id, :phoenix_token, :user_id, :ip_address])
  end
end

lib/ficdb/veil/session.ex
defmodule Ficdb.Veil.Session do
  @moduledoc """
  Veil's Session Schema
  """
  use Ecto.Schema
  import Ecto.Changeset
  alias Ficdb.Veil.User

  schema "veil_sessions" do
    field(:unique_id, :string)
    field(:phoenix_token, :string)
    field(:ip_address, :string)
    belongs_to(:user, User)

    timestamps()
  end

  def changeset(model, params \\ %{}) do
    model
    |> cast(params, [:unique_id, :phoenix_token, :user_id, :ip_address])
    |> validate_required([:unique_id, :phoenix_token, :user_id, :ip_address])
  end
end

lib/ficdb/veil/user.ex
defmodule Ficdb.Veil.User do
  @moduledoc """
  Veil's User Schema
  """
  use Ecto.Schema
  import Ecto.Changeset
  alias Ficdb.Veil.{Request, Session}
  alias Ficdb.FilenameRandomizer

  schema "veil_users" do
    field(:email, :string)
    field(:verified, :boolean, default: false)
    field :image, Ficdb.Image.Type
    field :username, :string
    field :role, Ficdb.RoleEnum, default: :user

    has_many(:requests, Request)
    has_many(:sessions, Session)
    has_many(:bookshelves, Ficdb.Directory.Bookshelf, foreign_key: :submitter_id)
    has_many(:submitted_fanfics, Ficdb.Directory.Fanfic, foreign_key: :submitter_id)
    has_many(:updated_fanfics, Ficdb.Directory.Fanfic, foreign_key: :submitter_id)

    timestamps()
  end

  def changeset(model, params \\ %{}) do
    params = FilenameRandomizer.put_random_filename params
    model
    |> cast(params, [:email, :verified, :username, :image, :role])
    |> validate_required([:email])
    |> validate_format(:email, ~r/^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$/)
    |> make_email_lowercase()
    |> unique_constraint(:email)
  end

  defp make_email_lowercase(changeset) do
    case changeset do
      %Ecto.Changeset{valid?: true, changes: %{email: email}} ->
        put_change(changeset, :email, email |> String.downcase())

      _ ->
        changeset
    end
  end
end

lib/ficdb_web/controllers/veil/fallback_controller.ex
defmodule FicdbWeb.Veil.FallbackController do
  @moduledoc """
  Translates controller action results into valid `Plug.Conn` responses.

  See `Phoenix.Controller.action_fallback/1` for more details.
  """
  require Logger
  use FicdbWeb, :controller
  alias Ficdb.Veil.User
#
#  def call(conn, {:error, {:closed, ""}}) do
#    Logger.error(fn -> "[Veil] Invalid Swoosh api key, update your config.exs" end)
#
#    render(conn, FicdbWeb.Veil.UserView, "new.html", changeset: User.changeset(%User{}))
#
#  end
#
#  def call(conn, {:error, :no_permission}) do
#    Logger.error(fn -> "[Veil] Invalid Request or Session" end)
#
#    render(conn, FicdbWeb.Veil.UserView, "new.html", changeset: User.changeset(%User{}))
#
#  end

  def call(conn, error) do
    IO.inspect("USER ERROR #{error}")
    conn
    |> put_flash(:error, "There was an error! Probably your email is malformed or your username is taken.")
    |> render(FicdbWeb.Veil.UserView, "new.html", changeset: User.changeset(%User{}))

  end

end

lib/ficdb_web/controllers/veil/session_controller.ex
defmodule FicdbWeb.Veil.SessionController do
  use FicdbWeb, :controller
  alias Ficdb.Veil
  use Breadcrumble

  plug :add_breadcrumb, name: 'Account', url: '/users/account'
  action_fallback(FicdbWeb.Veil.FallbackController)

  @doc """
  Creates a new session using a unique id sent by email.
  If creating the new session is successful, the user is verified and the request is deleted.
  """
  def create(conn, %{"request_id" => request_unique_id}) do
    with {:ok, request} <- Veil.get_request(request_unique_id),
         {:ok, user_id} <- Veil.verify(conn, request),
         {:ok, session} <- Veil.create_session(conn, user_id) do
      Task.start(fn -> Veil.verify_user(user_id) end)
      Task.start(fn -> Veil.delete(request) end)
      
      conn
      |> put_resp_cookie("session_unique_id", session.unique_id, max_age: 60*60*24*365)
      |> redirect(to: fanfic_path(conn, :index))
      
    else
      error ->
        IO.inspect(error)
    end
  end

  @doc """
  Deletes an existing session and logs the user out.
  """
  def delete(conn, %{"session_id" => session_unique_id}) do
    with {:ok, _session} <- Veil.delete_session(session_unique_id) do
      
      conn
      |> delete_resp_cookie("session_unique_id", max_age: 60*60*24*365)
      |> redirect(to: user_path(conn, :new))
      
    else
      error ->
        error
    end
  end
end

lib/ficdb_web/controllers/veil/user_controller.ex
defmodule FicdbWeb.Veil.UserController do
  use FicdbWeb, :controller
  use Breadcrumble

  alias Ficdb.Veil
  alias Ficdb.Veil.User
  alias Ficdb.Directory.{Fanfic, Review, Bookshelf}
  alias Ficdb.DateHelpers
  alias Ficdb.Authorization


  alias Ficdb.Repo

  action_fallback(FicdbWeb.Veil.FallbackController)

  #  plug :put_layout, :account_layout when action in [:show, :reviews, :bookshelves]

  plug(:scrub_params, "user" when action in [:create])



  def user_bookshelves(user_id),
      do: Bookshelf
          |> Bookshelf.user_bookshelves_query(user_id)
          |> Repo.all

  @doc """
  Shows the sign in form
  """
  def new(conn, _params) do
    add_breadcrumb(conn, name: "Auth", url: user_path(conn, :new))
    |> render("new.html", changeset: User.changeset(%User{}))
  end


  def show(conn, params) do
    user_id = params["id"] || Authorization.current_user_id(conn)
    is_my_account = !params["id"] || String.to_integer(params["id"]) == Authorization.current_user_id(conn)
    user = Veil.get_user(user_id)
    changeset = is_my_account && Veil.change_user(user)
    start = DateHelpers.now_microseconds

    add_breadcrumb(
      conn,
      name: "Account",
      url: user_path(conn, :show)
    )
    |> render(
         "account.html",
         changeset: changeset,
         user_bookshelves: user_bookshelves(user_id),
         user_id: user_id,
         user: user,
         is_my_account: is_my_account,
         benchmark: DateHelpers.now_microseconds - start
       )
  end

  def update(conn, %{"user" => user_params}) do
    user = Veil.get_user(Authorization.current_user_id(conn))

    case Veil.update_user(user, user_params) do
      {:ok, _user} ->
        conn
        |> put_flash(:info, "User updated successfully.")
        |> redirect(to: user_path(conn, :show))
      {:error, %Ecto.Changeset{} = changeset} ->
        conn
        |> put_flash(:error, "Invalid Image. Only .jpg, .jpeg, .gif, and .png files under 250kb without special characters or spaces allowed.")
        |> redirect(to: user_path(conn, :show))
    end
  end


  @doc """
  If needed, creates a new user, otherwise finds the existing one.
  Creates a new request and emails the unique id to the user.
  """

  def signup(
        conn,
        %{
          "user" => %{
            "email" => email,
            "username" => username
          }
        }
      ) when not is_nil(email) and not is_nil(username) do

    with {:ok, user} <- Veil.create_user(email, username) do
      sign_and_email(conn, user)
    else
      error ->
        error
    end

  end

  def login(
        conn,
        %{
          "user" => %{
            "email" => email
          }
        }
      ) when not is_nil(email) do

    if user = Veil.get_user_by_email(email) do
      sign_and_email(conn, user)
    end

  end

  defp sign_and_email(conn, %User{} = user) do
    with {:ok, request} <- Veil.create_request(conn, user),
         {:ok, email} <- Veil.send_login_email(conn, user, request) do

      add_breadcrumb(conn, name: "Auth", url: user_path(conn, :new))
      |> add_breadcrumb(name: "Check Your Email")
      |> render("show.html", user: user, email: email)

    else
      error ->
        error
    end
  end
end

lib/ficdb_web/views/veil/email_view.ex
defmodule FicdbWeb.Veil.EmailView do
  use FicdbWeb, :view

  def title(_, _assigns) do
    "Ficdb - Fanfic Database"
  end
end

lib/ficdb_web/views/veil/error_view.ex
defmodule FicdbWeb.Veil.ErrorView do
  use FicdbWeb, :view

  def title(_, _assigns) do
    "Ficdb - Fanfic Database"
  end
end

lib/ficdb_web/views/veil/session_view.ex
defmodule FicdbWeb.Veil.SessionView do
  use FicdbWeb, :view

  def title(_, _assigns) do
    "Ficdb - Fanfic Database"
  end
end

lib/ficdb_web/views/veil/user_view.ex
defmodule FicdbWeb.Veil.UserView do
  use FicdbWeb, :view

  def title(_, _assigns) do
    "Ficdb - Account"
  end
end

lib/ficdb_web/templates/veil/user/account.html.eex
<%= if @is_my_account, do: render FicdbWeb.SharedView, "_top_right_action_no_unpoly.html", text: "Sign out", path: session_path(@conn, :delete, @session_unique_id), dash: false %>

<div class="md:flex mt-4" up-keep id="account">
            <div class="">
                <div class="uk-tab uk-tab-left">
                        <div class="uk-active">

                        <a href="<%= "/veil/users/account/#{@user_id}" %>"  up-dash="#up-results">
                                                    <i class="jam jam-user text-lg inline-block align-middle pb-px mb-px"></i>
 Account
                        </a>
                        </div>

                        <div class="">
                        <a href="<%= "/veil/reviews?modal=true&search[submitter_id]=#{@user_id}" %>"  up-dash="#up-results">
                                                    <i class="jam jam-messages text-lg inline-block align-middle pb-px mb-px"></i>
 Reviews
                        </a>

                        <a href="<%= "/veil/users/fanfics?submitter_id=#{@user_id}" %>"  up-dash="#up-results">
                                                                            <i class="jam jam-messages text-lg inline-block align-middle pb-px mb-px"></i>
                         Submissions
                                                </a>
                        </div>

                        <%= for bookshelf <- @user_bookshelves do %>
                                <div>
                            <a href="<%= "/veil?modal=true&search[bookshelf]=#{bookshelf.id}" %>"  up-dash="#up-results">
                                                        <i class="jam jam-bookmark text-lg inline-block align-middle pb-px mb-px"></i>
 <%= Phoenix.Naming.humanize bookshelf.name %>
                            </a>
                            </div>
                        <% end %>
                </div>
            </div>
            <div class="flex-1 pl-4">
                 <div id="up-results">
                        <%= if @is_my_account, do: render "form.html", conn: @conn, changeset: @changeset, update: true, action: user_path(@conn, :update) %>
                        <%= if !@is_my_account, do: render "mini_account.html", conn: @conn, user: @user %>
                    </div>

            </div>
</div>

lib/ficdb_web/templates/veil/user/bookshelf.html.eex
<%= render FicdbWeb.SharedView, "_result_list.html", benchmark: @benchmark, conn: @conn, list: @fanfics, current_user_bookshelves: @current_user_bookshelves,  item_path: &fanfic_path/3 %>

lib/ficdb_web/templates/veil/user/form.html.eex
<%= form_for @changeset, @action, [multipart: true], fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

<%= if assigns[:signup] || assigns[:login] do %>

  <div class="my-4">
    <%= label f, :email, class: "block" %>
    <%= text_input f, :email, class: "uk-input", required: true %>
    <%= error_tag f, :email %>
  </div>
<% end %>

<%= if assigns[:signup] do %>
  <div class="my-4">
  <%= label f, :username, class: "block" %>
  <%= text_input f, :username, class: "uk-input", required: true %>
  <%= error_tag f, :username %>
  </div>
<% end %>

<%= if assigns[:update] do %>

  <div class="uk-margin-bottom">
  <%= text_input f, :username, class: "uk-input", disabled: true %>
  </div>


  <div class="uk-grid-small" uk-grid>
  <div class="uk-width-auto">
      <%= render FicdbWeb.SharedView, "_avatar.html", image: @changeset.data.image, model: @changeset %>
</div>
  <div class="uk-width-expand">
      <%= label f, "Avatar", class: "block" %>
      <div><%= file_input f, :image %></div>
      <%= error_tag f, :image %>
      </div>
    </div>

<% end %>



  <div class="mt-4">
    <%= submit assigns[:submit_text] || "Submit", class: "button" %>
  </div>
<% end %>

lib/ficdb_web/templates/veil/user/mini_account.html.eex
<article class="uk-comment uk-margin">
    <header class="uk-comment-header uk-grid uk-grid-small uk-flex-middle" uk-grid>
        <div class="uk-width-auto">
           <%= render FicdbWeb.SharedView, "_avatar.html", image: @user.image, model: @user, class: "uk-border-rounded" %>
        </div>
        <div class="uk-width-expand">
            <h4 class="uk-comment-title uk-margin-remove">
                <span><%= @user.username %></span>
            </h4>
            <ul class="uk-comment-meta uk-subnav uk-subnav-divider uk-margin-remove-top">
                <li>User since <%= relative(@user.inserted_at) %></li>
            </ul>
        </div>
    </header>
</article>

lib/ficdb_web/templates/veil/user/new.html.eex
<div class="flex mt-4 items-center items-stretch">
<div class="">
<div class="card inline-block mr-4 p-6">

<h4 class="mb-2 border-b border-albino pb-2">Sign Up</h4>

<%= render "form.html", changeset: @changeset, action: user_path(@conn, :signup), signup: true, submit_text: "Sign Up" %>
</div>
</div>
<div>
</div>
<div class="card ">
<h4 class="mb-2 border-b  border-albino pb-2">Login</h4>

<%= render "form.html", changeset: @changeset, action: user_path(@conn, :login), login: true, submit_text: "Login" %>
</div>
</div>

         Be sure to check our <%= link "FAQ page", to: page_path(@conn, :faq), class: "text-blue", "up-dash": "main" %> before you start reviewing!

lib/ficdb_web/templates/veil/user/reviews.html.eex
<div id="up-results">

<%= render FicdbWeb.SharedView, "_benchmark.html", list: @reviews, benchmark: assigns[:benchmark] %>

<%= render FicdbWeb.SharedView, "_review_list.html", conn: @conn, reviews: @reviews %>
</div>

lib/ficdb_web/templates/veil/user/show.html.eex
<h2>Verification email sent</h2>

<p>Please click the link to log in.</p>